services:
  filebrowser:
    image: hurlenko/filebrowser:latest
    environment:
      - UID=1000
      - GID=1000
      - TZ=America/Santiago
    ports:
      - 6005:8080
    volumes:
      - /media/ruta/disco:/data
      - ./fb-config:/config
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 2
        delay: 10s
        failure_action: rollback
        monitor: 60s
        max_failure_ratio: 0.1
        order: start-first
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
      endpoint_mode: vip
networks: {}
