services:
  filebrowser:
    image: hurlenko/filebrowser:latest
    environment:
      - UID=1000
      - GID=1000
      - TZ=America/Santiago
    ports:
      - 6005:8080
    volumes:
      - /media/ruta/disco:/data
      - ./fb-config:/config
    restart: unless-stopped
networks: {}