version: '3.8'
services:
  filebrowser:
    image: hurlenko/filebrowser:latest
    environment:
      - UID=1000
      - GID=1000
      - TZ=America/Santiago
    ports:
      - 6005:8080
    volumes:
      - /media/ruta/disco:/data
      - ./fb-config:/config
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
networks: {}